# Generated by Django 3.0.6 on 2020-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=200, verbose_name='lastName')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('dateDeNaissance', models.DateField(verbose_name='nom du manga')),
            ],
        ),
    ]
