# Generated by Django 3.0.6 on 2020-05-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rendu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='u_todolist', to='Rendu.User', verbose_name='User de la todos liste')),
            ],
        ),
        migrations.CreateModel(
            name='ItemToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_title', models.CharField(max_length=200, verbose_name="titre de l'items")),
                ('i_todoList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_items', to='Rendu.ToDoList', verbose_name='User de la todos liste')),
            ],
        ),
    ]
