# Generated by Django 3.0.6 on 2020-05-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rendu', '0003_auto_20200508_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_titre', models.CharField(max_length=200, verbose_name='titre de la todo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=200, verbose_name='lastName')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('dateDeNaissance', models.DateField(verbose_name='nom du manga')),
                ('todo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='u_todolist', to='Rendu.ToDoList', verbose_name='todos liste')),
            ],
        ),
        migrations.CreateModel(
            name='ItemToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_title', models.CharField(max_length=200, verbose_name="titre de l'items")),
                ('i_todoList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_items', to='Rendu.ToDoList', verbose_name='User de la todos liste')),
            ],
        ),
    ]
