# Generated by Django 3.0.6 on 2020-05-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendu', '0005_auto_20200508_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='t_listeItems',
            field=models.ManyToManyField(blank=True, to='Rendu.ItemToDoList'),
        ),
    ]
