# Generated by Django 3.0.6 on 2020-05-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendu', '0006_auto_20200508_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtodolist',
            name='i_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='nom du manga'),
        ),
    ]
